# scripts/setup.ps1
# ShikshaAI — One-command setup script for Windows (PowerShell)
# Run from the PROJECT ROOT: .\scripts\setup.ps1
# ─────────────────────────────────────────────────────────────────────────────

param(
    [switch]$SkipKnowledge  # pass -SkipKnowledge to skip the RAG ingestion step
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot   # project root regardless of where you run from

Write-Host ""
Write-Host "=====================================================================" -ForegroundColor Cyan
Write-Host "   SHIKSHAAI — ONE-COMMAND LOCAL DEVELOPMENT SETUP (Windows)"         -ForegroundColor Cyan
Write-Host "=====================================================================" -ForegroundColor Cyan
Write-Host ""

# ── [0] Verify prerequisites ──────────────────────────────────────────────────
Write-Host "[0/6] Checking prerequisites..." -ForegroundColor Yellow

$pythonCmd = $null
foreach ($cmd in @("python", "python3", "py")) {
    if (Get-Command $cmd -ErrorAction SilentlyContinue) {
        $ver = & $cmd --version 2>&1
        if ($ver -match "3\.(1[0-9]|[1-9][1-9])") {
            $pythonCmd = $cmd
            break
        }
    }
}
if (-not $pythonCmd) {
    Write-Host "   ERROR: Python 3.10+ is required." -ForegroundColor Red
    Write-Host "   Download from https://www.python.org/downloads/" -ForegroundColor Red
    exit 1
}
Write-Host "   OK  Python: $( & $pythonCmd --version 2>&1 )" -ForegroundColor Green

if (-not (Get-Command "node" -ErrorAction SilentlyContinue)) {
    Write-Host "   ERROR: Node.js is required." -ForegroundColor Red
    Write-Host "   Download LTS from https://nodejs.org/" -ForegroundColor Red
    exit 1
}
Write-Host "   OK  Node.js: $( node --version )" -ForegroundColor Green
Write-Host "   OK  npm:     $( npm --version )" -ForegroundColor Green

# ── [1] Environment files ─────────────────────────────────────────────────────
Write-Host ""
Write-Host "[1/6] Setting up environment files..." -ForegroundColor Yellow

# Root .env (for docker-compose and reference)
if (-not (Test-Path "$Root\.env")) {
    Copy-Item "$Root\.env.example" "$Root\.env"
    Write-Host "   Created: .env  (root)" -ForegroundColor Green
} else {
    Write-Host "   Exists:  .env  (root)" -ForegroundColor DarkGray
}

# backend/.env  — this is what the FastAPI server actually reads
if (-not (Test-Path "$Root\backend\.env")) {
    $backendEnvContent = @"
# ShikshaAI Backend Environment — auto-generated by setup.ps1
APP_NAME=ShikshaAI
APP_VERSION=1.0.0
DEBUG=True

# Database — SQLite (zero-config, works without Docker)
DATABASE_URL=sqlite:///./shikshaai.db

# JWT Authentication
SECRET_KEY=shikshaai-change-this-in-production-$(Get-Random -Maximum 999999)
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Google Gemini AI  — get a FREE key at https://aistudio.google.com
# AI Tutor works without this key using local NCERT template fallback
GEMINI_API_KEY=placeholder

# CORS
ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
"@
    Set-Content "$Root\backend\.env" $backendEnvContent
    Write-Host "   Created: backend/.env" -ForegroundColor Green
} else {
    Write-Host "   Exists:  backend/.env" -ForegroundColor DarkGray
}

# frontend/.env.local  — Next.js reads NEXT_PUBLIC_* from here
if (-not (Test-Path "$Root\frontend\.env.local")) {
    Set-Content "$Root\frontend\.env.local" "NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1"
    Write-Host "   Created: frontend/.env.local" -ForegroundColor Green
} else {
    Write-Host "   Exists:  frontend/.env.local" -ForegroundColor DarkGray
}

# ── [2] Python virtual environment ───────────────────────────────────────────
Write-Host ""
Write-Host "[2/6] Setting up Python virtual environment..." -ForegroundColor Yellow

if (-not (Test-Path "$Root\backend\venv")) {
    & $pythonCmd -m venv "$Root\backend\venv"
    Write-Host "   Created: backend/venv" -ForegroundColor Green
} else {
    Write-Host "   Exists:  backend/venv" -ForegroundColor DarkGray
}

$pip  = "$Root\backend\venv\Scripts\pip.exe"
$pyEx = "$Root\backend\venv\Scripts\python.exe"

Write-Host "   Upgrading pip, setuptools, wheel..." -ForegroundColor DarkGray
& $pip install --upgrade pip setuptools wheel --quiet

Write-Host "   Installing backend packages from requirements.txt..." -ForegroundColor DarkGray
& $pip install -r "$Root\backend\requirements.txt" --quiet
Write-Host "   OK  Backend Python dependencies installed." -ForegroundColor Green

# ── [3] Frontend Node dependencies ───────────────────────────────────────────
Write-Host ""
Write-Host "[3/6] Installing frontend Node.js dependencies..." -ForegroundColor Yellow

Push-Location "$Root\frontend"
npm install --silent
Pop-Location
Write-Host "   OK  npm packages installed." -ForegroundColor Green

# ── [4] Database initialisation ──────────────────────────────────────────────
Write-Host ""
Write-Host "[4/6] Initialising database & seeding content..." -ForegroundColor Yellow
Write-Host "   (Using SQLite — no Docker required)" -ForegroundColor DarkGray

Push-Location "$Root\backend"
& $pyEx reset_and_seed_content.py
Pop-Location
Write-Host "   OK  Database schema created and content seeded." -ForegroundColor Green

# ── [5] RAG knowledge base ingestion ─────────────────────────────────────────
if (-not $SkipKnowledge) {
    Write-Host ""
    Write-Host "[5/6] Ingesting NCERT knowledge base for AI Tutor..." -ForegroundColor Yellow
    & $pyEx "$Root\scripts\ingest_knowledge.py"
    Write-Host "   OK  NCERT knowledge base ingested." -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "[5/6] Skipped knowledge ingestion (-SkipKnowledge flag set)." -ForegroundColor DarkGray
}

# ── [6] Done ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "   SETUP COMPLETE!                                                  " -ForegroundColor Green
Write-Host "=====================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "   Next step — start the application:" -ForegroundColor White
Write-Host "   > .\scripts\start.ps1" -ForegroundColor Cyan
Write-Host ""
Write-Host "   Then open your browser at: http://localhost:3000" -ForegroundColor White
Write-Host ""
Write-Host "   OPTIONAL: For AI Tutor features, add your FREE Gemini API key:" -ForegroundColor Yellow
Write-Host "   1. Visit https://aistudio.google.com and create a free API key" -ForegroundColor DarkGray
Write-Host "   2. Edit backend\.env and set GEMINI_API_KEY=your_key_here" -ForegroundColor DarkGray
Write-Host ""
