#!/usr/bin/env bash
# scripts/setup.sh
# ShikshaAI — One-command setup script for macOS / Linux
# Run from the PROJECT ROOT:  bash scripts/setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$(dirname "$SCRIPT_DIR")"   # project root regardless of where you run from

echo ""
echo "====================================================================="
echo "   ShikshaAI — ONE-COMMAND LOCAL DEVELOPMENT SETUP (macOS/Linux)"
echo "====================================================================="
echo ""

# ── [0] Verify prerequisites ──────────────────────────────────────────────────
echo "[0/6] Checking prerequisites..."

PYTHON_CMD=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        VER=$("$cmd" --version 2>&1 | grep -oP '3\.\K\d+' | head -1)
        if [ -n "$VER" ] && [ "$VER" -ge 10 ]; then
            PYTHON_CMD="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo "   ERROR: Python 3.10+ is required."
    echo "   macOS: brew install python  |  Ubuntu: sudo apt install python3"
    exit 1
fi
echo "   OK  Python: $($PYTHON_CMD --version)"

if ! command -v node &>/dev/null; then
    echo "   ERROR: Node.js is required."
    echo "   Download LTS from https://nodejs.org/"
    exit 1
fi
echo "   OK  Node.js: $(node --version)"
echo "   OK  npm:     $(npm --version)"

# ── [1] Environment files ─────────────────────────────────────────────────────
echo ""
echo "[1/6] Setting up environment files..."

# Root .env
if [ ! -f "$ROOT/.env" ]; then
    cp "$ROOT/.env.example" "$ROOT/.env"
    echo "   Created: .env  (root)"
else
    echo "   Exists:  .env  (root)"
fi

# backend/.env — what FastAPI actually reads
if [ ! -f "$ROOT/backend/.env" ]; then
    RAND=$RANDOM
    cat > "$ROOT/backend/.env" <<EOF
# ShikshaAI Backend Environment — auto-generated by setup.sh
APP_NAME=ShikshaAI
APP_VERSION=1.0.0
DEBUG=True

# Database — SQLite (zero-config, works without Docker)
DATABASE_URL=sqlite:///./shikshaai.db

# JWT Authentication
SECRET_KEY=shikshaai-change-this-in-production-${RAND}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Google Gemini AI  — get a FREE key at https://aistudio.google.com
# AI Tutor works without this key using local NCERT template fallback
GEMINI_API_KEY=placeholder

# CORS
ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
EOF
    echo "   Created: backend/.env"
else
    echo "   Exists:  backend/.env"
fi

# frontend/.env.local — Next.js reads NEXT_PUBLIC_* from here
if [ ! -f "$ROOT/frontend/.env.local" ]; then
    echo "NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1" > "$ROOT/frontend/.env.local"
    echo "   Created: frontend/.env.local"
else
    echo "   Exists:  frontend/.env.local"
fi

# ── [2] Python virtual environment ───────────────────────────────────────────
echo ""
echo "[2/6] Setting up Python virtual environment..."

if [ ! -d "$ROOT/backend/venv" ]; then
    $PYTHON_CMD -m venv "$ROOT/backend/venv"
    echo "   Created: backend/venv"
else
    echo "   Exists:  backend/venv"
fi

PIP="$ROOT/backend/venv/bin/pip"
PYEX="$ROOT/backend/venv/bin/python"

echo "   Upgrading pip, setuptools, wheel..."
"$PIP" install --upgrade pip setuptools wheel -q

echo "   Installing backend packages from requirements.txt..."
"$PIP" install -r "$ROOT/backend/requirements.txt" -q
echo "   OK  Backend Python dependencies installed."

# ── [3] Frontend Node dependencies ───────────────────────────────────────────
echo ""
echo "[3/6] Installing frontend Node.js dependencies..."

cd "$ROOT/frontend"
npm install --silent
cd "$ROOT"
echo "   OK  npm packages installed."

# ── [4] Database initialisation ──────────────────────────────────────────────
echo ""
echo "[4/6] Initialising database & seeding content..."
echo "   (Using SQLite — no Docker required)"

cd "$ROOT/backend"
"$PYEX" reset_and_seed_content.py
cd "$ROOT"
echo "   OK  Database schema created and content seeded."

# ── [5] RAG knowledge base ingestion ─────────────────────────────────────────
echo ""
echo "[5/6] Ingesting NCERT knowledge base for AI Tutor..."
"$PYEX" "$ROOT/scripts/ingest_knowledge.py"
echo "   OK  NCERT knowledge base ingested."

# ── [6] Done ──────────────────────────────────────────────────────────────────
echo ""
echo "====================================================================="
echo "   SETUP COMPLETE!"
echo "====================================================================="
echo ""
echo "   Next step — start the application:"
echo "   $ bash scripts/start.sh"
echo ""
echo "   Then open your browser at: http://localhost:3000"
echo ""
echo "   OPTIONAL: For AI Tutor features, add your FREE Gemini API key:"
echo "   1. Visit https://aistudio.google.com and create a free API key"
echo "   2. Edit backend/.env and set GEMINI_API_KEY=your_key_here"
echo ""
